---
#title: Research
bibliography: myrefs.bib
nocite: |
  @Almeida2023ApplicationOD, @Silva2016EfficientEA, @Ribeiro2022TowardsTA, @Flix2023VisionbasedCM
---

# Publications

::: {#refs}
:::

# Advisor

<!-- - 2023 - Irina Soares "Previsão de colisões para veículos aéreos não tripulados de asa fixa" / "Collision avoidance for fixed-wing Unmanned Aereal Vehicles"
- 2023 - João Branco - "Estimação cooperative para um sistema de seguimento de alvos em ambiente marítimo" / "Cooperative estimation for target tracking in maritime environment"
- 2023 - Francisco Matilde - "Study of the Use of Synthetic Images in the Training of Neural Networks for Detection with UAVs"
- 2023 - José Rocha - "Design and Implementation of a Vision-based Autoland System"
- 2022 - Miguel Félix - "Target tracking control system for multi-UAV maritime applications"
- 2022 - João Alves "Software architecture for low-cost UAVs – An application considering automatic target tracking mission scenarios" [Extended abstract](https://www.academiafa.edu.pt/paginas/352academiafa/ficheiros/noticias/2023/Revista%20Cient%C3%ADfica%20da%20Academia%20da%20For%C3%A7a%20A%C3%A9rea%20N%C2%BA%2013%20Publica%C3%A7%C3%A3o%202023.pdf#page=55)
- 2017 - Fábio Lourenço "Desenvolvimento de Sistema de Telemetria sobre Vídeo para UAS da FAP" [Extended abstract](https://www.academiafa.edu.pt/paginas/revcientif1571214007_footer1571213530_352academiafa/ficheiros/revcientif/revista-ci-ntifica-vers-o-final-publicada_534.pdf#page=63) -->


- 2023 - "Previsão de colisões para veículos aéreos não tripulados de asa fixa" / "Collision avoidance for fixed-wing Unmanned Aereal Vehicles"
- 2023 - "Estimação cooperative para um sistema de seguimento de alvos em ambiente marítimo" / "Cooperative estimation for target tracking in maritime environment"
- 2023 - "Study of the Use of Synthetic Images in the Training of Neural Networks for Detection with UAVs"
- 2023 - "Design and Implementation of a Vision-based Autoland System"
- 2022 - "Target tracking control system for multi-UAV maritime applications"
- 2022 - "Software architecture for low-cost UAVs – An application considering automatic target tracking mission scenarios" [Extended abstract](https://www.academiafa.edu.pt/paginas/352academiafa/ficheiros/noticias/2023/Revista%20Cient%C3%ADfica%20da%20Academia%20da%20For%C3%A7a%20A%C3%A9rea%20N%C2%BA%2013%20Publica%C3%A7%C3%A3o%202023.pdf#page=55)
- 2017 - "Desenvolvimento de Sistema de Telemetria sobre Vídeo para UAS da FAP" [Extended abstract](https://www.academiafa.edu.pt/paginas/revcientif1571214007_footer1571213530_352academiafa/ficheiros/revcientif/revista-ci-ntifica-vers-o-final-publicada_534.pdf#page=63)
